version: "3.8"

services:
  tfjs-worker:
    build: .
    container_name: tfjs-worker-container
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    command: ["ts-node", "index.ts"]
